name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore dependencies
        run: dotnet restore OpenRouter.sln
      - name: Build
        run: dotnet build OpenRouter.sln --configuration Release --no-restore
      - name: Test
        run: dotnet test OpenRouter.sln --configuration Release --no-build --collect:"XPlat Code Coverage"
      - name: Report Coverage
        uses: danielpalme/ReportGenerator-GitHub-Action@5.2.4
        with:
          reports: '**/coverage.cobertura.xml'
          targetdir: 'coveragereport'
          reporttypes: 'HtmlInline_AzurePipelines;Cobertura'
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coveragereport
      - name: Update coverage badge in README
        if: github.event_name == 'push'
        shell: pwsh
        run: ./.github/workflows/update-coverage-badge.ps1
      - name: Commit and push README update
        if: github.event_name == 'push'
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add README.md
          git diff --cached --quiet || git commit -m "Update coverage badge [skip ci]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
