name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore dependencies
        run: dotnet restore OpenRouter.sln
      - name: Build
        run: dotnet build OpenRouter.sln --configuration Release --no-restore
      - name: Test
        run: dotnet test OpenRouter.sln --configuration Release --no-build --collect:"XPlat Code Coverage"
      - name: Report Coverage
        uses: danielpalme/ReportGenerator-GitHub-Action@5.2.4
        with:
          reports: '**/coverage.cobertura.xml'
          targetdir: 'coveragereport'
          reporttypes: 'HtmlInline_AzurePipelines;Cobertura'
      - name: Output code coverage percent to log
        shell: pwsh
        run: |
          $coverageFile = Get-ChildItem -Recurse -Filter coverage.cobertura.xml | Select-Object -First 1
          if (-not $coverageFile) { Write-Host 'No coverage.cobertura.xml file found.'; exit 1 }
          [xml]$xml = Get-Content $coverageFile.FullName
          $rootLineRate = $xml.coverage.'line-rate'
          $lineRate = [math]::Round(([double]$rootLineRate) * 100, 2)
          Write-Host "##[group]CODE COVERAGE SUMMARY"
          Write-Host "Total line coverage: $lineRate%"
          Write-Host "##[endgroup]"
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coveragereport
